CUDA_VISIBLE_DEVICES=0 llamafactory-cli train \
    --stage sft \
    --do_predict \
    --model_name_or_path /root/.cache/modelscope/hub/models/Qwen/Qwen3-1.7B \
    --adapter_name_or_path /root/autodl-tmp/Qwen3_lora/checkpoint-393  \
    --eval_dataset alpaca_gpt4_zh,identity,adgen_local \
    --dataset_dir data \
    --template qwen \
    --finetuning_type lora \
    --output_dir /root/autodl-tmp/Qwen3_lora/predict \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 1024 \
    --preprocessing_num_workers 16 \
    --per_device_eval_batch_size 1 \
    --max_samples 20 \
    --predict_with_generate